export const listingsData = [
    {
      id: '1',
      title: 'S 500 Sedan',
      price: '$548',
      registration: 'DN63WPZ',
      postCode: 'S63',
      weight: '1320 KG',
      engineCode: 'M472D20C',
      engineSize: '1995',
      transmission: 'MANUAL 6 Gears',
      distance: '107 mi',
      views: '8',
      image: require('../assets/car.png'),
    },
    {
      id: '1',
      title: 'GLA 250 SUV',
      price: '$548',
      registration: 'DN63WPZ',
      postCode: 'S63',
      weight: '1320 KG',
      engineCode: 'M472D20C',
      engineSize: '1995',
      transmission: 'MANUAL 6 Gears',
      distance: '107 mi',
      views: '8',
      image: require('../assets/car2.png'),
    },
    {
      id: '2',
      title: 'S 500 Sedan',
      price: '$548',
      registration: 'DN63WPZ',
      postCode: 'S63',
      weight: '1320 KG',
      engineCode: 'M472D20C',
      engineSize: '1995',
      transmission: 'MANUAL 6 Gears',
      distance: '107 mi',
      views: '8',
      image: require('../assets/car.png'),
    },
    {
      id: '3',
      title: 'GLA 250 SUV',
      price: '$548',
      registration: 'DN63WPZ',
      postCode: 'S63',
      weight: '1320 KG',
      engineCode: 'M472D20C',
      engineSize: '1995',
      transmission: 'MANUAL 6 Gears',
      distance: '107 mi',
      views: '8',
      image: require('../assets/car2.png'),
    },
  ];