default_platform(:ios)

platform :ios do

  lane :screenshots do
    snapshot(
      scheme: "car scrap staging",
      output_directory: "./fastlane/screenshots",
      clear_previous_screenshots: true,
      override_status_bar: true
    )
  end

  private_lane :setup do
    api_key = app_store_connect_api_key(
      key_id: "YUFRC8H2Y6",
      issuer_id: "84ab350a-e81d-4ec1-a405-fd8ee68492a4",
      key_content: ENV["APP_STORE_CONNECT_API_KEY"],
      is_key_content_base64: false
    )
    latest_build = latest_testflight_build_number(
      api_key: api_key,
      app_identifier: "com.carscrape.rniap"
    )
    increment_build_number(
      xcodeproj: "carScrap.xcodeproj",
      build_number: latest_build + 1
    )
    get_provisioning_profile(
      api_key: api_key,
      app_identifier: "com.carscrape.rniap",
      provisioning_name: "carScrap AppStore",
      ignore_profiles_with_different_name: false,
      output_path: "/tmp"
    )
    update_code_signing_settings(
      use_automatic_signing: false,
      path: "carScrap.xcodeproj",
      team_id: "3ZZTDYP4ZM",
      code_sign_identity: "Apple Distribution",
      profile_uuid: lane_context[SharedValues::SIGH_UUID]
    )
    api_key
  end

  lane :staging do
    increment_version_number(
      xcodeproj: "carScrap.xcodeproj",
      bump_type: "patch"
    )
    api_key = setup
    build_app(
      workspace: "carScrap.xcworkspace",
      scheme: "car scrap staging",
      export_method: "app-store",
      xcargs: "ENVFILE=.env.staging",
      buildlog_path: "~/Library/Logs/gym",
      clean: true
    )
    upload_to_testflight(
      api_key: api_key,
      distribute_external: false,
      notify_external_testers: false
    )
  end

  lane :production do
    api_key = setup
    build_app(
      workspace: "carScrap.xcworkspace",
      scheme: "carScrapProduction",
      export_method: "app-store",
      xcargs: "ENVFILE=.env.production",
      clean: true
    )
    upload_to_app_store(
      api_key: api_key,
      submit_for_review: false,
      automatic_release: false,
      skip_metadata: true,
      skip_screenshots: true,
      run_precheck_before_submit: false
    )
  end

end
