default_platform(:ios)

platform :ios do

  lane :staging do
    api_key = app_store_connect_api_key(
      key_id: "YUFRC8H2Y6",
      issuer_id: "84ab350a-e81d-4ec1-a405-fd8ee68492a4",
      key_content: ENV["APP_STORE_CONNECT_API_KEY"],
      is_key_content_base64: false
    )
    increment_build_number(xcodeproj: "carScrap.xcodeproj")
    update_code_signing_settings(
      use_automatic_signing: true,
      path: "carScrap.xcodeproj",
      team_id: "3ZZTDYP4ZM"
    )
    build_app(
      workspace: "carScrap.xcworkspace",
      scheme: "car scrap staging",
      export_method: "app-store",
      xcargs: "ENVFILE=.env.staging -allowProvisioningUpdates",
      buildlog_path: "~/Library/Logs/gym"
    )
    upload_to_testflight(
      api_key: api_key,
      distribute_external: false,
      notify_external_testers: false
    )
  end

  lane :production do
    api_key = app_store_connect_api_key(
      key_id: "YUFRC8H2Y6",
      issuer_id: "84ab350a-e81d-4ec1-a405-fd8ee68492a4",
      key_content: ENV["APP_STORE_CONNECT_API_KEY"],
      is_key_content_base64: false
    )
    increment_build_number(xcodeproj: "carScrap.xcodeproj")
    update_code_signing_settings(
      use_automatic_signing: true,
      path: "carScrap.xcodeproj",
      team_id: "3ZZTDYP4ZM"
    )
    build_app(
      workspace: "carScrap.xcworkspace",
      scheme: "carScrapProduction",
      export_method: "app-store",
      xcargs: "ENVFILE=.env.production -allowProvisioningUpdates"
    )
    upload_to_testflight(
      api_key: api_key,
      distribute_external: false,
      notify_external_testers: false
    )
  end

end
