default_platform(:ios)

platform :ios do

  lane :staging do
    increment_build_number(xcodeproj: "carScrap.xcodeproj")
    update_code_signing_settings(
      use_automatic_signing: true,
      path: "carScrap.xcodeproj",
      team_id: "3ZZTDYP4ZM"
    )
    build_app(
      workspace: "carScrap.xcworkspace",
      scheme: "car scrap staging",
      export_method: "app-store",
      xcargs: "ENVFILE=.env.staging -allowProvisioningUpdates",
      buildlog_path: "~/Library/Logs/gym"
    )
    upload_to_testflight(
      api_key_path: "fastlane/app_store_connect_api_key.json",
      distribute_external: false,
      notify_external_testers: false
    )
  end

  lane :production do
    increment_build_number(xcodeproj: "carScrap.xcodeproj")
    update_code_signing_settings(
      use_automatic_signing: true,
      path: "carScrap.xcodeproj",
      team_id: "3ZZTDYP4ZM"
    )
    build_app(
      workspace: "carScrap.xcworkspace",
      scheme: "carScrapProduction",
      export_method: "app-store",
      xcargs: "ENVFILE=.env.production -allowProvisioningUpdates"
    )
    upload_to_testflight(
      api_key_path: "fastlane/app_store_connect_api_key.json",
      distribute_external: false,
      notify_external_testers: false
    )
  end

end
